### ISSUE TITLE
Todo 1

### ISSUE THREAD

**Issue by GeoffreyPlitt** [GeoffreyPlitt/twitter_bot#1]
Leads
- [x] New branch
- [x] Remove delays
- [x] Change to a much smaller seed, someone I don't mind making mistakes with, for now. 
- [x] Remove memcache for the "entire list" result, I'm not even going to use that anymore.
- [x] Add API call for fetching most recent tweets of an account.
- [x] Add API call for fetching RT'ers of a tweet
- [x] Does the paging-result carry numeric information, like "5 of 10 pages" ?
- [x] While-loop grabs leads, hydreates, filters dups, saves to DB
- [x] If I get this far, merge branch to master.
- [x] Print a "phase" banner. Phases = [Leads, Follows, DM, Unfollows, Sleep]
- [x] Add a "phases" config key, put constants in there
- [x] Fix images too small?
- [x] Filter rows with missing usernames
- [x] filtering to just leafs
- [x] Use app-auth for Leads, User-auth for Follows
- [x] Filter out self

Following
- [x] Get the eligible leads in a random order, and do following, just 1 at first.
- [x] Achieve rate-limiting by default with an hourly-trigger assumption.

Then
- [x] Running once per hour

Follow-back detection
- [x] Follow-back detection (this is another phase).

**Comment by GeoffreyPlitt** [comment]
Twitter rate Limits
- Follow ratio rule: you cannot follow more than 10% of how many users follow you.
- Max 400 follows per 24h. Verified can follow 1000!
- Churning, duplicating another accounts users, or using too short a time period, can all lead to getting blocked.
- I also wonder if API usage (as opposed to browser simulation) is at fault.

**Comment by GeoffreyPlitt** [comment]
DMs
- [x] do some quick rate-limiting
- [ ] set max_to_send_per_phase_run back to 40 once things are working.
- [ ] bootstrap my existing followers into the DM queue?
- [ ] DM user with a friendly message, "If you like __ you'll like my show". "My show is like theirs, news and punchlines". Link to my trailer (evergreen link), and the trailer should have an endscreen link to latest episode (via playlist). (fetched with youtube API?)
- [ ] DM with CTA button so I can track the clicks?
- [ ] If I encounter rate-limiting, it's time to make a uniform util around sleeping/retrying. Use the headers from the twitter API call, it provides a timestamp.
- [ ] Also, I could stop the DM automation, still automate the rest to get leads,  then DM them using browser-automation or just manually.

Unfollowing
- [ ] Unfollow

Later
- [ ] github auth
- [ ] Reporting - Express server, table view. data-table with sort, filter.
