### ISSUE TITLE
Todo 2

### ISSUE THREAD

**Issue by GeoffreyPlitt** [GeoffreyPlitt/twitter_bot#4]
- [ ] Am I filtering to only English speakers? Sometimes I get people from other countries
- [ ] Update my twitter-bot seeds: Remove a few, and add some Kimmel/Colbert/BillMaher show accounts
- [ ] Any more missed opportunities? I should calm down the logs, compact them, so it's easier to see the top counts achieved in each phase.
- [ ] Grab more than 16, separate those I'm already following (and mark them in DB as following so it doesn't grab them again). That way I'm always following 16 per hour. Right now I'm missing opportunities.
- [ ] This user seems to not speak english, see if my filters can figure that out: r.db('twitter_bot').table('users').filter({screen_name:'Mywaterlepus'})
- [ ] Unfollowing
- [ ]  add timeout retry
- [ ] Order leads by recency, or purge really old leads?
- [ ] Try adding personalization to the DMs - extract name from full-name my splitting on space?
- [ ] List my new followers this way, and DM them this way - so I am DMing people from ALL campaigns, no matter how they followed me. The Twitter API returns the followers in order of "newer follower first", so on the first hit (a follower listed in your stored version of the list) you can stop looking for new followers.
